pipeline {
    agent any

    environment {
        REPORT_DIR = "test-output"
    }

    stages {
        stage('Checkout Code') {
            steps {
                git url: 'https://github.com/techybiky/TestNGFramework.git', branch: 'main'
            }
        }

        stage('Build and Test') {
            steps {
                dir('selenium-pom-framework') {
                    sh 'mvn clean test'
                }
            }
        }

        stage('Publish TestNG Report') {
            steps {
                dir('selenium-pom-framework') {
                    publishHTML(target: [
                        allowMissing: false,
                        alwaysLinkToLastBuild: true,
                        keepAll: true,
                        reportDir: 'test-output',
                        reportFiles: 'index.html',
                        reportName: 'TestNG Report'
                    ])
                }
            }
        }
    }

    post {
        always {
            dir('selenium-pom-framework') {
                junit 'target/surefire-reports/*.xml'
            }
        }
    }
}
